Add support for env in podtemplate
tektoncd/pipeline pull request #3566
Opened 2020-11-30 03:21 UTC by piyush-garg

This will help to specify env default, env at pipelinerun, and taskrun level. Env in pod template will take
precedence over one defined in step and step template

Env at pipelinerun and taskrun level will take precedence over
the one in the default pod template

Fix #1606

/kind feature

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Add support for env in default podTemplate, pipelinerun podTemplate and taskrun podTemplate
```

2020-11-30 09:44 UTC, chmouel commented
This look good, maybe add an example ? The same way we have on [that example](https://github.com/tektoncd/pipeline/blob/4fdd018d/examples/v1beta1/taskruns/run-steps-as-non-root.yaml) ?

2020-11-30 16:36 UTC, jerop requested changes
please add the env field to the supported fields table in https://github.com/tektoncd/pipeline/blob/ab723e9e79d358b6397cc62a199ba4c489ee3480/docs/podtemplates.md

2020-12-08 04:51 UTC, piyush-garg commented
@chmouel @vdemeester @jerop I have updated the PR with tests, docs and examples

2020-12-08 11:51 UTC, vdemeester approved these changes

2020-12-08 14:36 UTC, bobcatfish reviewed
I'm surprised we didn't want to go ahead with a TEP on this @vdemeester ?

I traced back in the API working group notes and found [our discussion on july 20](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.6kdniqxkggld) 

I know it's a pain to ask for a TEP after the work is already done, but I feel like if it wasn't already done, a TEP would be totally reasonable? Esp. given that this is controversial - or at least it is controversial to me b/c I think folks could use this in such a way that Tekton will replicate the mistakes of other CI/CD systems (which is ironically the motivation for this feature afaik, e.g. migrating from jenkins)

A couple things we might want to cover in a TEP:

- do we want to do this in the pod template or do we want this to be a top level feature? (so it's more obvious) this would also give us more control over which containers these env vars are provided to if we want it
- one thing in the working group I suggested was do we want to make it so that Tasks have to opt into this functionality somehow, i.e. so when you look at a task it's obvious it will also accept some undeclared list of env vars

/hold

2020-12-08 14:36 UTC, bobcatfish commented on docs/podtemplates.md
> +			<td>Specifies a list of environments that all containers within the Pod will be populated</td>
nit: environments -> environment variables?

2020-12-08 15:56 UTC, vdemeester commented
> I'm surprised we didn't want to go ahead with a TEP on this @vdemeester ?
> 
> I traced back in the API working group notes and found [our discussion on july 20](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.6kdniqxkggld)
> 
> I know it's a pain to ask for a TEP after the work is already done, but I feel like if it wasn't already done, a TEP would be totally reasonable? Esp. given that this is controversial - or at least it is controversial to me b/c I think folks could use this in such a way that Tekton will replicate the mistakes of other CI/CD systems (which is ironically the motivation for this feature afaik, e.g. migrating from jenkins)
> 
> A couple things we might want to cover in a TEP:
> 
> * do we want to do this in the pod template or do we want this to be a top level feature? (so it's more obvious) this would also give us more control over which containers these env vars are provided to if we want it
> * one thing in the working group I suggested was do we want to make it so that Tasks have to opt into this functionality somehow, i.e. so when you look at a task it's obvious it will also accept some undeclared list of env vars
> 
> /hold

Agreed on all those :upside_down_face:

2021-05-22 07:45 UTC, closed without merging

2021-11-29 22:04 UTC, afrittoli commented
@vdemeester @piyush-garg any plan to bring this back to live? AFAIK most of the discussion already happened, it was only a matter of formalising it via TEP?