Fix broken link in doc
tektoncd/pipeline pull request #3634
Opened 2020-12-13 01:10 UTC by vincent-pli

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

2020-12-14 05:52 UTC, jerop requested changes

2020-12-15 00:48 UTC, vincent-pli commented on docs/tekton-controller-performance-configuration.md
> +Sometimes, above default values can't meet performance requirements, then you need to overwrite these values. You can modify them in the [tekton controller deployment](https://github.com/tektoncd/pip
Thanks, agree with you, ./../config/ should be better

2020-12-15 17:13 UTC, jerop commented
@vincent-pli thanks for making the changes!

please also fill out the sections of the pull request template, specifically the changes description including the kind label and release notes (even if it's NONE)

2020-12-16 09:05 UTC, vincent-pli commented
/kind bug

2020-12-16 15:02 UTC, jerop reviewed
/lgtm
/meow

2020-12-16 17:20 UTC, merged