Remove tekton.dev/clusterTask label from taskrun of clustertasks
tektoncd/pipeline pull request #3764
Opened 2021-02-15 10:46 UTC by piyush-garg

This will remove the label tekton.dev/clusterTask label from taskruns which
are referencing a clusterTask. This was marked deprecated in v0.12.0

Fix #2533

/kind cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

For pull requests with a release note:

```release-note
Remove tekton.dev/clusterTask label from taskrun of clustertasks
```

2021-02-15 10:47 UTC, piyush-garg commented
/hold

cc @vdemeester @bobcatfish @sbwsg 

This is regarding the removal of deprecation thing. Let me know if any other changes are required for this

2021-02-15 19:17 UTC, AlanGreene requested changes
Can you update the PR title, release note, and commit message to indicate the correct label?

It's actually the `tekton.dev/task` label that's being removed.

2021-02-16 15:01 UTC, piyush-garg commented
> Can you update the PR title, release note, and commit message to indicate the correct label?
> 
> It's actually the `tekton.dev/task` label that's being removed.

@AlanGreene Thanks for this. Mistakes while typing. Fixed these now.

2021-02-22 15:04 UTC, sbwsg commented
This looks good to me.  Suggest also updating `docs/deprecations.md` to remove mention of `tekton.dev/task` label on ClusterTasks.

2021-03-09 17:39 UTC, sbwsg commented
I'll remove the deprecation in a follow-up PR.

/approve

2021-03-09 17:40 UTC, vdemeester reviewed
/lgtm

2021-03-09 17:44 UTC, pritidesai commented
thank you @sbwsg @vdemeester 🙏 
/hold cancel

2021-03-09 18:08 UTC, merged