Implement Step and Sidecar Overrides for TaskRun
tektoncd/pipeline pull request #4598
Opened 2022-02-18 18:40 UTC by lbernick

# Changes
This implements [TEP-0094: Configuring Resources at Runtime](https://github.com/tektoncd/community/blob/main/teps/0094-configuring-resources-at-runtime.md).
StepOverrides and SidecarOverrides were added to the API in a previous commit.
This commit allows them to override resource requirements specified in the Task spec.
The same merging strategy that is currently used for stepTemplate is also used for
step and sidecar overrides, except that only the resources field of the container is overridden,
and unlike with templates, the overrides take precedence over the Task spec.

Closes #4326.

Tested E2E locally. Happy to split into separate PRs if this would be helpful.

/kind feature

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
[Feature] Implement Step and Sidecar Overrides for TaskRun
```

2022-02-18 18:41 UTC, lbernick commented
/assign wlynch

Feel free to unassign yourself if you don't have time to review! Just assigning you since you reviewed the TEP pretty thoroughly.

2022-02-24 15:38 UTC, lbernick commented
/hold
Decided to split into multiple PRs. First is #4617.

2022-03-03 20:49 UTC, sbwsg commented
/lgtm

2022-03-04 10:01 UTC, jerop reviewed
thanks @lbernick - looks good, left a few comments

2022-03-04 15:52 UTC, lbernick commented
/test pull-tekton-pipeline-integration-tests

2022-03-04 16:00 UTC, lbernick commented
/test pull-tekton-pipeline-alpha-integration-tests

2022-03-07 16:46 UTC, sbwsg commented
/lgtm

Cheers @lbernick !

2022-03-08 16:55 UTC, wlynch requested changes
mostly lgtm! just a few nits regarding exporting funcs.

2022-03-08 20:00 UTC, lbernick commented on pkg/pod/pod.go
> +	}
Discussed offline and reopened #1605 with comments.

2022-03-08 20:01 UTC, lbernick commented on pkg/reconciler/taskrun/validate_resources_test.go
> +			err := taskrun.ValidateOverrides(context.Background(), tc.ts, tc.trs)
done. I left `ValidateResolvedTaskResources` exported as it's used in the pipelinerun reconciler to validate the param/resource bindings passed from the pipeline -> pipelinerun -> taskrun.

2022-03-08 20:59 UTC, sbwsg commented
The `workspace-in-sidecar` example failed in the alpha integration run but is [a known flake](https://github.com/tektoncd/pipeline/issues/4169). Unfortunately no logs were printed but I think it's safe to retry.

/test pull-tekton-pipeline-alpha-integration-tests

/lgtm

2022-03-09 19:30 UTC, lbernick commented
@wlynch would you mind taking another look at this?

2022-03-09 21:27 UTC, wlynch approved these changes
/lgtm

2022-03-11 10:33 UTC, vdemeester approved these changes

2022-03-11 13:15 UTC, sbwsg commented
Integration run failed on a yaml example. Let's see if it repeats.

Workspace-in-sidecar failed in the alpha integration run, no logs because the step's container was waiting to start.

/test pull-tekton-pipeline-integration-tests

/test pull-tekton-pipeline-alpha-integration-tests

2022-03-11 13:43 UTC, merged