Fix for ResourceQuotaConflictError
tektoncd/pipeline pull request #5252
Opened 2022-08-02 13:13 UTC by yachna

Recreation of pod for podRecreationLimit number of times if it runs into ResourceQuotaConflictError Error i.e https://github.com/kubernetes/kubernetes/issues/67761

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

2022-08-02 14:05 UTC, SaschaSchwarze0 commented
/kind bug

2022-08-03 21:42 UTC, dibyom commented
Shouldn't this already already be handled in https://github.com/tektoncd/pipeline/blob/94055d92c120a6010f3d61a821e45dea4f893a74/pkg/reconciler/taskrun/taskrun.go#L577?

Also see https://github.com/tektoncd/pipeline/issues/734

2022-08-04 07:10 UTC, SaschaSchwarze0 commented
> Shouldn't this already already be handled in
> 
> https://github.com/tektoncd/pipeline/blob/94055d92c120a6010f3d61a821e45dea4f893a74/pkg/reconciler/taskrun/taskrun.go#L577
> ?
> 
> Also see #734

Hi @dibyom, we are not facing an exceeded resource quota. We face the problem that when you create a resource (for example a Pod) that is constrained by a resource quota, then the creation can fail because of conflicts while updating the resource quota status (that's the long-standing Kubernetes issue that @yachna mentioned, https://github.com/kubernetes/kubernetes/issues/67761).

But maybe that function is where we need to move the retry logic @yachna, with maybe a requeue after one second.

2022-08-04 15:13 UTC, dibyom commented
/ok-to-test

2022-08-05 10:52 UTC, yachna commented
/retest

2022-08-05 10:53 UTC, yachna commented
/retest-required

2022-08-09 09:31 UTC, SaschaSchwarze0 requested changes

2022-08-09 09:31 UTC, SaschaSchwarze0 commented on pkg/reconciler/taskrun/taskrun.go
> +	c.handlePodCreationError(tr, err)
@yachna this addition needs to go away

2022-08-09 10:07 UTC, yachna commented on pkg/reconciler/taskrun/taskrun.go
> +	c.handlePodCreationError(tr, err)
Removed

2022-08-11 08:03 UTC, SaschaSchwarze0 commented
@dibyom we are ready here, code has been moved :-)

2022-08-11 16:22 UTC, dibyom commented
Thanks @yachna and @SaschaSchwarze0 The code looks fine to me. One request - could we update the commit message with a bit more description around what the issue was that this commit solves (like the description [here](https://github.com/tektoncd/pipeline/pull/5252#issuecomment-1204855613) so that it meets our commit guidelines: https://github.com/tektoncd/community/blob/main/standards.md#commits

2022-08-18 14:55 UTC, vdemeester approved these changes

2022-08-22 03:45 UTC, yachna commented
> Thanks @yachna and @SaschaSchwarze0 The code looks fine to me. One request - could we update the commit message with a bit more description around what the issue was that this commit solves (like the description [here](https://github.com/tektoncd/pipeline/pull/5252#issuecomment-1204855613) so that it meets our commit guidelines: https://github.com/tektoncd/community/blob/main/standards.md#commits

Hi @dibyom 

Thanks for the suggestion. I have updated the commit message accordingly.

2022-08-30 22:31 UTC, dibyom commented
/lgtm

2022-08-31 06:55 UTC, SaschaSchwarze0 commented
/test pull-tekton-pipeline-integration-tests
/test pull-tekton-pipeline-alpha-integration-tests

2022-08-31 13:42 UTC, abayer commented
/retest

2022-08-31 14:12 UTC, merged