Pipelines Docs Cleanup
tektoncd/pipeline pull request #6117
Opened 2023-02-07 16:46 UTC by geriom

# Changes

- Update weights to group similar docs on website
- Add missing front matter to docs where it's missing
- Delete obsolete docs

@afrittoli classified the current Pipelines documentation and reported issues with some documents missing the front matter, these docs show up as blank spaces in the left nav at https://tekton.dev/docs/pipelines/

[This spreadsheet](https://docs.google.com/spreadsheets/d/1HknnR5FDSPgLJlI7kbtPsUlvL1nGvYeIZA7vKti05os/edit?usp=sharing) has the full list of docs, the classifications, those marked to be deleted, and the new suggested order.

The new categories, by doc `weight`, are:

- 100s: Tekton usage docs 
- 200s: Tekton Resources
- 300s: Tekton Features
- 400s: References and API Features

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2023-02-08 09:51 UTC, vdemeester approved these changes

2023-02-08 09:51 UTC, vdemeester commented
> tide — Not mergeable. PR can't be rebased
This is weird, seems like it's the case for all our PRs... (cc @abayer @afrittoli )

2023-02-08 13:04 UTC, AlanGreene requested changes
Thanks @geriom, the new order makes a lot more sense to me 👍 

Small typo, otherwise looks good.

2023-02-08 13:04 UTC, AlanGreene commented on docs/bundle-resolver.md
> +linkTitle: "Bundles Reesolver"
```suggestion
linkTitle: "Bundles Resolver"
```

2023-02-08 13:04 UTC, AlanGreene commented on docs/trusted-resources.md
> +linkTitle: "Trusted Sources"
Should this be `Trusted Resources`?

2023-02-08 15:11 UTC, geriom commented on docs/bundle-resolver.md
> +linkTitle: "Bundles Reesolver"
fixed

2023-02-08 15:11 UTC, geriom commented on docs/trusted-resources.md
> +linkTitle: "Trusted Sources"
fixed

2023-02-13 20:56 UTC, jerop reviewed
/lgtm

2023-02-13 20:57 UTC, jerop commented
/test pull-tekton-pipeline-go-coverage-df

2023-02-13 23:30 UTC, merged