add pipelinetask metadata validation
tektoncd/pipeline pull request #6513
Opened 2023-04-10 12:59 UTC by cugykw

# Changes

Add parameter validation of metatdata in pipelinetask taskSpec. 
Avoid invalid metadata causing PR to run stuck.

Fixes:  #6453 

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Add parameter validation of metatdata in pipelinetask taskSpec. 
```

2023-04-12 16:03 UTC, dibyom commented
@cugykw doesn't this also need to be ported to the v1/pipeline_types.go?

2023-04-12 17:49 UTC, chitrangpatel commented
/assign

2023-04-13 04:51 UTC, cugykw commented
> doesn't this also need to be ported to the v1/pipeline_types.go?
@dibyom i have updated.

2023-05-24 08:29 UTC, vdemeester requested changes
I tend to agree with @lbernick, but this means we would need to make sure we are not letting the PipelineRun or TaskRun getting stuck though.

2023-07-21 10:21 UTC, cugykw commented
> I think it would be better to let k8s handle validation of metadata. From #6453 it sounds like when the controller failed to create a taskrun, the pipelinerun got stuck and was still marked as running. It sounds to me like we should address that issue directly. It doesn't fail as fast as the solution in this PR, but I'm worried we could still run into the same problem if taskrun creation fails for other reasons.

@lbernick @vdemeester I'm so sorry that I've noticed lately that I haven't been replying to everyone. I very much agree with this opinion. When our users had this error at the beginning, I thought it was a pending situation again. In fact, this error will not lead to a pending situation, and the displayed error message is relatively clear.

2023-07-25 13:24 UTC, cugykw commented
/close

2023-07-25 13:24 UTC, closed without merging