fix alpha propagated object params docs
tektoncd/pipeline pull request #6753
Opened 2023-05-31 19:20 UTC by Yongxuanzhang

# Changes
Propagated object params should be in beta feature since object params (TEP75) is in beta and propagating params is in stable (TEP107).

/kind cleanup

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2023-05-31 19:20 UTC, Yongxuanzhang commented
/assign @chitrangpatel

2023-05-31 19:35 UTC, chitrangpatel commented
/lgtm

2023-05-31 19:38 UTC, Yongxuanzhang commented
/retest 
pull-tekton-pipeline-build-tests — Pod scheduling timeout. 

2023-06-02 16:35 UTC, jerop requested changes

2023-06-02 16:35 UTC, jerop commented on docs/pipelineruns.md
> +Object params is [beta features](./additional-configs.md#beta-features).
```suggestion
Object params is a [beta feature](./additional-configs.md#beta-features).
```

2023-06-02 17:41 UTC, Yongxuanzhang commented on docs/pipelineruns.md
> +Object params is [beta features](./additional-configs.md#beta-features).
Thank you!

2023-06-05 15:40 UTC, chuangw6 commented
/lgtm

2023-06-07 21:10 UTC, QuanZhang-William commented
Thanks! lgtm!

2023-06-08 19:28 UTC, jerop approved these changes

2023-06-08 20:28 UTC, merged