Update releases.md
tektoncd/pipeline pull request #6851
Opened 2023-06-20 19:47 UTC by lbernick

This commit updates releases.md to reflect the v0.49.0 release.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- n/a Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- n/a Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- n/a Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2023-06-20 22:05 UTC, AlanGreene requested changes
Thanks @lbernick, just a couple of extra bits that need to be updated.

2023-06-20 22:05 UTC, AlanGreene commented on releases.md
>  ### v0.48
```suggestion
### v0.49
```

2023-06-20 22:05 UTC, AlanGreene commented on releases.md
> +- **Initial Release**: [v0.49.0][v0-49-0] (2023-03-17)
Release date needs to be updated here

```suggestion
- **Latest Release**: [v0.49.0][v0-49-0] (2023-06-20) ([docs][v0-49-0-docs], [examples][v0-49-0-examples])
- **Initial Release**: [v0.49.0][v0-49-0] (2023-06-20)
```

2023-06-21 12:21 UTC, lbernick commented
thanks @AlanGreene, fixed! also added info for v0.47.2

2023-06-21 12:38 UTC, JeromeJu approved these changes
/lgtm

2023-06-21 12:58 UTC, merged