kind/feature : populate-params-and-results-to-workspace-bindings (wip)
tektoncd/pipeline pull request #7503
Opened 2023-12-19 18:17 UTC by ericzzzzzzz

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2023-12-20 17:05 UTC, chitrangpatel commented
/ok-to-test

2024-01-03 09:21 UTC, vdemeester requested changes
Looks good, but I have one question : is it intentional to not support the `csi` workspace binding ? I don't really see any reason to support all (pvc, claimtemplate, secret, configmap and projected) but `csi` 🤔

2024-01-03 15:18 UTC, ericzzzzzzz commented
@vdemeester 
> Looks good, but I have one question : is it intentional to not support the `csi` workspace binding ? I don't really see any reason to support all (pvc, claimtemplate, secret, configmap and projected) but `csi` 🤔

ahh, sorry I thought we just wanted the fields listed on the issue. I'll add support for `csi`,

2024-01-05 10:50 UTC, vdemeester approved these changes

2024-01-05 18:23 UTC, JeromeJu approved these changes

2024-01-09 17:46 UTC, chitrangpatel commented
/assign

2024-01-10 15:21 UTC, chitrangpatel commented on pkg/reconciler/pipelinerun/resources/apply.go
> +			}
Needs coverage.

2024-01-10 15:22 UTC, chitrangpatel commented on pkg/reconciler/pipelinerun/resources/apply.go
> +				}
Needs coverage

2024-01-10 15:22 UTC, chitrangpatel commented on pkg/reconciler/pipelinerun/resources/apply.go
> +			}
needs coverage.

2024-01-10 15:23 UTC, chitrangpatel requested changes
Almost lgtm. Just need coverage on the places I highlighted I think. They are untested.

2024-01-15 17:46 UTC, merged