fix: prevent modification of annotations on completed TaskRuns
tektoncd/pipeline pull request #7603
Opened 2024-01-23 11:37 UTC by l-qing

In TaskRun, the annotation `pipeline.tekton.dev/release` records the version information of the pipeline. If the Pipeline is updated, the annotation in the completed TaskRuns should not be modified.

* https://github.com/tektoncd/pipeline/blob/e1c7828e0fad1006b6477a5ce0468a2a3182060b/pkg/reconciler/taskrun/taskrun.go#L142-L155
* https://github.com/tektoncd/pipeline/blob/e1c7828e0fad1006b6477a5ce0468a2a3182060b/pkg/reconciler/taskrun/taskrun.go#L295-L319
* https://github.com/tektoncd/pipeline/blob/e1c7828e0fad1006b6477a5ce0468a2a3182060b/pkg/reconciler/taskrun/taskrun.go#L650-L657

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
fix: prevent modification of annotations on completed TaskRuns
```
/kind bug

2024-01-23 17:01 UTC, khrm reviewed
/ok-to-test

2024-01-23 17:24 UTC, vdemeester requested changes
This is most likely going to be a problem as some things need to update annotations once the TaskRun or PipelineRun is done. An example is the chains component that signs outputs once the run is done and adds annotations to the object once signed.

cc @tektoncd/core-maintainers @tektoncd/chains-maintainers

2024-01-23 21:21 UTC, lcarva commented
> This is most likely going to be a problem as some things need to update annotations once the TaskRun or PipelineRun is done. An example is the chains component that signs outputs once the run is done and adds annotations to the object once signed.

Yup! I believe this is also true for the Tekton Results project. cc @tektoncd/results-maintainers 

@l-qing, could provide more context on why the suggested changes are desired?

2024-01-24 00:28 UTC, l-qing commented
> could provide more context on why the suggested changes are desired?

As described above: After upgrading the Pipeline, I found that the Annotations `pipeline.tekton.dev/release` of the historical TaskRun have all been modified. I believe this operation is not expected.
There may be several thousand TaskRuns in my environment.
The Pipeline I'm using is a custom-built version, such annotations changes happen quite frequently, unlike the community ones.

I might not be very familiar with tekton result.
But looking at the code logic here, it seems like it won't affect other components.
Because this change, only affects those taskruns that were already in a done state before entering reconcile. Originally they weren't doing much anyway.

https://github.com/tektoncd/pipeline/blob/e1c7828e0fad1006b6477a5ce0468a2a3182060b/pkg/reconciler/taskrun/taskrun.go#L107-L155

I have updated the description to elucidate the impact.
https://github.com/tektoncd/pipeline/blob/469906fc47089a091bd3c946dc62577d25762c52/pkg/reconciler/taskrun/taskrun.go#L310-L313

2024-01-24 12:36 UTC, khrm reviewed
@vdemeester 
I don't think this PR stops tekton-chains or tekton-results from adding annotations.  It just blocks this function https://github.com/tektoncd/pipeline/blob/39cdda048453d6d4b8e206be9310c30db9f8faff/pkg/reconciler/taskrun/taskrun.go#L650

Changes aren't in the validator code but reconciler. It's okay if the annotation for a completed pipelinerun/taskrun is not updated by the pipeline controllers.
Is my understanding correct, @l-qing ?

2024-01-24 15:26 UTC, l-qing commented
> @vdemeester I don't think this PR stops tekton-chains or tekton-results from adding annotations. It just blocks this function
> 
> https://github.com/tektoncd/pipeline/blob/39cdda048453d6d4b8e206be9310c30db9f8faff/pkg/reconciler/taskrun/taskrun.go#L650
> 
> Changes aren't in the validator code but reconciler. It's okay if the annotation for a completed pipelinerun/taskrun is not updated by the pipeline controllers. Is my understanding correct, @l-qing ?

Yes, that's exactly what I mean.

In the reconcile of the PipelineRun, I noticed that there is no location where the `pipeline.tekton.dev/release` annotations are set, so I reverted the code related to PipelineRun. 😆

2024-01-29 09:20 UTC, vdemeester approved these changes

2024-02-09 01:38 UTC, l-qing commented
/retest-required

2024-02-09 16:48 UTC, dibyom approved these changes
Thanks @l-qing - I updated the release note to make it a bit clearer that this is only preventing modification of the annotations that are set by the pipeline controller.

/lgtm

2024-02-09 17:31 UTC, merged

2024-02-10 14:14 UTC, l-qing commented
> Thanks @l-qing - I updated the release note to make it a bit clearer that this is only preventing modification of the annotations that are set by the pipeline controller.

Thanks!