Fix: use upstream const for error messages
tektoncd/pipeline pull request #7780
Opened 2024-03-20 17:10 UTC by lunarwhite

Fix https://github.com/tektoncd/pipeline/issues/7466

/kind cleanup

# Changes

* Import `k8s.io/apiserver/pkg/registry/generic/registry` to use `OptimisticLockErrorMsg`
* Update the related test case
* Remove the local constant defination
* Update package dependencies by using `./hack/update-deps.sh`

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2024-03-22 14:45 UTC, lunarwhite commented
Hi @JeromeJu, could you please take a look at this PR when you get a chance? It will fix https://github.com/tektoncd/pipeline/issues/7466. Thanks in advance!

2024-03-27 00:37 UTC, vdemeester requested changes
I am not really a fan of adding a new dependency and ~94k lines of code for one constant in 2 lines of code 😅. This feels overkill, and is, imo, a good example of when "a little duplication" is better than something else 🙃

2024-04-02 21:51 UTC, lunarwhite commented
@vdemeester Thanks for your input. It does make sense.

Do you have any suggestions, or should we leave it as it is for now?

2024-04-03 02:31 UTC, vdemeester commented
> @vdemeester Thanks for your input. It does make sense.
> 
> Do you have any suggestions, or should we leave it as it is for now?

Yeah either leaving as is or creating our own constant (and a comment explaining why we don’t import the library)

2024-04-05 17:14 UTC, lunarwhite commented
Hi @vdemeester, it should be addressed now. You could take a look when you have time. Thx!

2024-04-05 17:36 UTC, vdemeester approved these changes
/meow

2024-04-05 17:39 UTC, JeromeJu commented
Thanks @lunarwhite 
/lgtm

2024-04-06 00:55 UTC, khrm reviewed
/ok-to-test

2024-04-06 01:33 UTC, merged