[WIP] Fix Crash due to Matrix Validation in non Matrix Pipeline
tektoncd/pipeline pull request #8088
Opened 2024-07-01 19:04 UTC by khrm

Fixes #8086
# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2024-07-01 19:04 UTC, khrm reviewed
/kind bug

2024-07-02 06:51 UTC, khrm commented
/retest

2024-07-03 06:19 UTC, khrm commented
Are tests failing due to WIP?

2024-07-03 06:19 UTC, khrm commented
/retest

2024-07-03 07:04 UTC, vdemeester requested changes
@khrm can we have a regression test ? For example, having the reproducer posted in the issue (or something simpler) in the example tests ?

2024-07-03 07:25 UTC, khrm commented
@vdemeester Sure. I am adding that.

2024-07-03 09:51 UTC, khrm commented on pkg/apis/pipeline/v1/pipeline_validation.go
> +		if !t.IsMatrixed() && !hasMatrixTask {
That's why I have `hasMatrixTask`. If PipelineRun already has a MatrixTask, then we will proceed with validation anyway.

2024-07-03 10:05 UTC, khrm commented on pkg/apis/pipeline/v1/pipeline_validation.go
> +		if !t.IsMatrixed() && !hasMatrixTask {
I have moved this check upwards.

2024-07-03 10:14 UTC, khrm commented
@vdemeester I have added one regression test.

2024-07-03 10:38 UTC, piyush-garg commented on pkg/apis/pipeline/v1/pipeline_validation.go
> +	if !hasMatrix {
better

```
	if hasMatrix {
		errs = errs.Also(validateTaskResultsFromMatrixedPipelineTasksConsumed(tasks))
	}
```

2024-07-03 11:01 UTC, khrm commented on pkg/apis/pipeline/v1/pipeline_validation.go
> +	if !hasMatrix {
Yes. That looks better.

2024-07-03 11:04 UTC, khrm commented on pkg/apis/pipeline/v1/pipeline_validation.go
> +	if !hasMatrix {
Done.

2024-07-05 09:48 UTC, vdemeester reviewed
@khrm any reason for the regression test to be in the upgrade tests and not in the exemples tests ?

2024-07-19 04:22 UTC, khrm commented
@vdemeester Examples aren't run as upgrade tests. We need a more complex pipelines for upgrade tests.

2024-07-25 10:21 UTC, afrittoli commented
#8086 is marked as closed by #8089, but this is meant to fix the same issue. Do we need to reopen #8086, was the fix incomplete?

2024-07-31 15:43 UTC, khrm commented
@afrittoli I would say it's a partial fix. Error can happen in some other flow also.

2024-09-24 14:18 UTC, afrittoli commented
> @vdemeester Examples aren't run as upgrade tests. We need a more complex pipeline for upgrade tests.

I think @vdemeester question was about why did you modify the upgrade test instead of the regular integration test.

2025-08-19 19:15 UTC, waveywaves commented
Hi @khrm, thank you for your work on this, will you be continuing work on this ?

2025-08-19 19:40 UTC, khrm commented
I think we can close this for now. There was another pr which solve this.

2025-08-20 05:27 UTC, khrm commented
Oh. As I said, we fixed one flow, but error can happen in this flow also. I needed to change test for this. Let me check.

2025-10-06 10:04 UTC, vdemeester commented
@khrm this needs a rebase 👼🏼

2026-06-09 09:54 UTC, closed without merging